### ISSUE TITLE
Split UI and dictionary code?

### ISSUE THREAD

**Issue by Arya-Elfren** [ymndoseijin/doseijisho#2]
If you wanted to support multiple frontends (you've mentioned TUIs but I could also see a CLI/dmenu/fzf style interface being supported) I would split the dictionary handling from the UI code so that each interface could access a "uniform" dictionary interface.

**Comment by ymndoseijin** [comment]
It's mostly separated, with all of the dictionary interface being on defs.zig, MeCab still isn't decoupled from GTK though, so there's that. After that, the plan is to start doing a CLI interface, specially so one can hook it up with some sort of dmenu script. I've also seen a couple of EPWING Vim plugins, so it might be interesting to implement that as well

**Comment by ymndoseijin** [comment]
closed with [new commit](https://github.com/ymndoseijin/doseijisho/commit/100e3bfd8df8fa2020a98716f805c08bf61ba698)
